spring.application.name=api0704
spring.datasource.url=jdbc:mysql://localhost:3306/api_0704
spring.datasource.username=root
spring.datasource.password=

# Configuraci�n de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
