spring.application.name=api0804
# URL de conex�o (ajuste para o seu banco)
spring.datasource.url=jdbc:mysql://localhost:3306/api_0804
spring.datasource.username=root
spring.datasource.password=

# Hibernate: Cria/atualiza as tabelas automaticamente (use 'update' em dev)
spring.jpa.hibernate.ddl-auto=update

# Mostra as queries SQL no console (�til para debug)
spring.jpa.show-sql=true
